apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: result
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: result
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/example-voting-app-main-back-tier: "true"
        io.kompose.network/example-voting-app-main-front-tier: "true"
        io.kompose.service: result
    spec:
      containers:
        - command:
            - nodemon
            - --inspect=0.0.0.0
            - server.js
          image: result
          name: result
          ports:
            - containerPort: 80
              hostPort: 5001
              protocol: TCP
            - containerPort: 9229
              hostIP: 127.0.0.1
              hostPort: 9229
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/local/app
              name: result-claim0
      restartPolicy: Always
      volumes:
        - name: result-claim0
          persistentVolumeClaim:
            claimName: result-claim0
