apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vote
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/example-voting-app-main-back-tier: "true"
        io.kompose.network/example-voting-app-main-front-tier: "true"
        io.kompose.service: vote
    spec:
      containers:
        - image: vote
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 5
          name: vote
          ports:
            - containerPort: 80
              hostPort: 5000
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/local/app
              name: vote-claim0
      restartPolicy: Always
      volumes:
        - name: vote-claim0
          persistentVolumeClaim:
            claimName: vote-claim0
